# taken from https://dev.to/abulka/comment/1dh3k thanks!
name: Build
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          run_install: true
          version: 6.26.x
      - name: Build
        run: |
        npx pkg --compress Brotli -t node16 index.js --out-path build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
